DROP TABLE IF EXISTS LogCleanupSummaries;
DROP TABLE IF EXISTS Tariffs;
DROP TABLE IF EXISTS Funds;
DROP TABLE IF EXISTS Organizations;
DROP TABLE IF EXISTS Receptions;
DROP TABLE IF EXISTS UploadCounters;
